apiVersion: v2
name: blogchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 11.1.19
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled, global.postgresql.enabled
