replicaCount: 1

image:
  repository: bandirom/django-blog
  pullPolicy: Always
  tag: "1.2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true


service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: blog.raspberry.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5
  httpGet:
    path: /application/health/
    port: http
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5
  httpGet:
    path: /application/health/
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolumeClaim:
  storageClassName: ""
  storageSize: 3Gi

postgresql:
  enabled: true
  auth:
    username: "blog-user"
    password: "blog-password"
    database: "blog-db"
    enablePostgresUser: true
    postgresPassword: "postgres-password"
  secret: false
  host: false


redis:
  enabled: true
  architecture: standalone
  port: "6379"
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

project:
  secretKey: "abcEFG"
  postgresUser: "postgres"
  healthCheckUrl: "/application/health/"
  microserviceName: "Blog Microservice"

celery:
  args:
    - "celery"
    - "-A"
    - "src"
    - "worker"
    - "-l"
    - "info"
